### ISSUE TITLE
Friendly with loading JS that interacts with the DOM?

### ISSUE THREAD

**Issue by rdmurphy** [filamentgroup/loadJS#18]
Hello!

So we've been using `loadJS` on [our site](http://txlege.texastribune.org/), but there's something weird going on. The script loads JavaScript that sets up the shutter open/close functionality – but we've noticed that sometimes the shutters don't work. It's pretty random.

Is this potentially a case of the JavaScript controlling the shutters getting loaded before the DOM, or is there something else we're missing? Potentially solved via a `window.onload()`?

**Comment by scottjehl** [comment]
Since request latency is involved here, there's no guarantee when your script will finish loading. It could execute before DOM ready (especially when cached), or long after that. 

You'll need to write any DOM-dependent logic with this in mind. If you use a framework that treats "dom ready" as an instant callback any time after the DOM is ready (like jQuery or Shoestring), this should work on its own with a dom ready event. If not, you'll need to not only listen for domcontentloaded but also check ready state. That's where a central dom ready function comes in handy, because there are some browser quirks to consider.

fwiw, shoestring's handler works well with loadJS and it's vanilla JS. It's here if you want to crib from it: https://github.com/filamentgroup/shoestring/blob/master/src/core/ready.js

**Comment by rdmurphy** [comment]
Thanks @scottjehl! I'll check it out.
