### ISSUE TITLE
Support polyfill methodology of <link rel="preload">, similar to loadCSS

### ISSUE THREAD

**Issue by silenceisgolden** [filamentgroup/loadJS#23]
This use case comes to mind:

```
// This script has only the fancier and larger menu JS included.
<link rel="preload" as="script" href="/desktop-menu.js" media="(min-width: 768px)" onload="loadJS(this.href)">

// This script has only the mobile menu JS included, or maybe this is omitted entirely and CSS used for the menu on mobile devices.
<link rel="preload" as="script" href="/mobile-menu.js" media="(max-width: 767px)" onload="loadJS(this.href)">
```

With the current discussion about module loaders and h2, I'm unsure if a new library would be more accurate for this issue or not (or just System.import), so discussion is very welcome.

**Comment by scottjehl** [comment]
Just getting to this now, sorry/thanks. 
So, I think this idea is good to consider. Link rel=preload has an edge over `script[async]` in that it supports media queries. That said, I can't recall deciding to load a script or not based on media queries, mostly because we typically want a script to be ready to apply after an orientation change or resize. 

We'll have to think on this, but I would like to explore whether the rel=preload polyfill might be better as its own new library. In this case, I think we'd modify very little to use either loadCSS or loadJS depending on the `as` attribute value. This line would mostly be it I think: https://github.com/filamentgroup/loadCSS/blob/master/src/cssrelpreload.js#L22

**Comment by scottjehl** [comment]
Late followup. I don't think we're interested in supporting this idea in this particular project, but I did blog about how it would look to create such a workflow for conditional JS loading. 

https://www.filamentgroup.com/lab/preload-ctm.html 

Thanks!
